fix(python3-scipy): add pybind11 to class-target DEPENDS
Add python3-pybind11 to DEPENDS for target builds as scipy searches for
its pkg-config file in recipe-sysroot. Otherwise, it calls
pybind11-config as a fallback, which returns hosts paths for includes.
This might then cause build failures:

    /usr/include/python3.12/pyconfig.h:3:12: fatal error: x86_64-linux-gnu/python3.12/pyconfig.h: No such file or directory
    3 | #  include <x86_64-linux-gnu/python3.12/pyconfig.h>